name       : gem
version    : 0.9.1
release    : 7
source     :
    - https://download.tuxfamily.org/gem/releases/gem-0.9.1.tar.xz : 89e82ab4bdb7f5ee121263ca748d065b0422f93e24bc64c6e5ac9ae67b7cf75f
license    : GPL-3.0
component  : games.emulator
summary    : Graphical Emulators Manager
description: |
    A front-end to manage easily your retro games.
builddeps  :
    - python-setuptools
rundeps    :
    - python-gobject
    - python-setuptools
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm644 gem.desktop $installdir/usr/share/applications/gem.desktop
    install -Dm644 gem/icons/ui/gem.svg $installdir/usr/share/pixmaps/gem.svg
