name       : gem
version    : 0.7.1
release    : 1
source     :
    - https://download.tuxfamily.org/gem/releases/gem-0.7.1.tar.xz : deb8096f01d5fd0e9d567d8253b1993b66be4914ab644ccda42c8449be9059d5
license    : GPL-3.0
component  : games.emulator
summary    : Graphical Emulators Manager
description: |
    A front-end to manage easily your retro games.
builddeps  :
    - python-setuptools
rundeps  :
    - python3-gobject
    - python-setuptools
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm644 gem.desktop $installdir/usr/share/applications/gem.desktop
    install -Dm644 gem/icons/ui/gem.svg $installdir/usr/share/pixmaps/gem.svg
