name       : gem
version    : 0.9
release    : 3
source     :
    - https://download.tuxfamily.org/gem/releases/gem-0.9.tar.xz : 357a74739b0eabaa9cf82f2a8363ad3de4b91ed1dee765a3dbfa992d97bfbde0
license    : GPL-3.0
component  : games.emulator
summary    : Graphical Emulators Manager
description: |
    A front-end to manage easily your retro games.
builddeps  :
    - python-setuptools
rundeps  :
    - python3-gobject
    - python-setuptools
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm644 gem.desktop $installdir/usr/share/applications/gem.desktop
    install -Dm644 gem/icons/ui/gem.svg $installdir/usr/share/pixmaps/gem.svg
