name       : gem
version    : 0.8
release    : 2
source     :
    - https://download.tuxfamily.org/gem/releases/gem-0.8.tar.xz : 48f9e72b7ecb48ea27f727f20de57863ade02369cc2e536fe8d3dea65ce85c75
license    : GPL-3.0
component  : games.emulator
summary    : Graphical Emulators Manager
description: |
    A front-end to manage easily your retro games.
builddeps  :
    - python-setuptools
rundeps  :
    - python3-gobject
    - python-setuptools
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm644 gem.desktop $installdir/usr/share/applications/gem.desktop
    install -Dm644 gem/icons/ui/gem.svg $installdir/usr/share/pixmaps/gem.svg
